# Generated by Django 3.0.7 on 2020-07-24 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brick_version', models.CharField(choices=[('V1.1', 'V1.1')], max_length=20)),
                ('haystack_version', models.CharField(choices=[('V3.9.9', '3.9.9')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PointMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brick_class', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('haystack_tagset', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.Mapper')),
            ],
        ),
    ]
