# Generated by Django 3.0.7 on 2020-07-24 08:21

from django.db import migrations
from mapp.resources.utils import create_initial_mapper, infer_points


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_mapper),
        migrations.RunPython(infer_points)
    ]
