# Generated by Django 3.0.7 on 2020-07-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_auto_20200731_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haystackpointtype',
            old_name='tags',
            new_name='marker_tags',
        ),
    ]
