# Generated by Django 3.0.7 on 2020-07-31 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_auto_20200731_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='brickpointtype',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapp.BrickVersion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haystackpointtype',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackVersion'),
            preserve_default=False,
        ),
    ]
