# Generated by Django 3.0.7 on 2020-08-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_auto_20200731_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaystackEquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haystack_tagset', models.CharField(max_length=150)),
                ('marker_tags', models.ManyToManyField(to='mapp.HaystackMarkerTag')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackVersion')),
            ],
        ),
    ]
