# Generated by Django 3.0.7 on 2020-08-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_auto_20200810_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtypemap',
            name='brick_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapp.BrickVersion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointtypemap',
            name='haystack_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackVersion'),
            preserve_default=False,
        ),
    ]
