# Generated by Django 3.0.7 on 2020-08-24 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_auto_20200824_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtypemap',
            name='brick_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapp.BrickPointType'),
        ),
        migrations.AlterField(
            model_name='pointtypemap',
            name='haystack_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackPointType'),
        ),
    ]
