# Generated by Django 3.0.7 on 2020-08-24 02:25
# Generated by Django 3.0.7 on 2020-08-24 01:59

from django.db import migrations

from mapp.resources.migration_utils import generate_point_type_map, add_map_to_db


def add_inference_versions(apps, schema_editor):
    InferenceVersion = apps.get_model('mapp', 'InferenceVersion')
    ivs = ['0.1.7b5', '0.1.9a1']
    for iv in ivs:
        temp = InferenceVersion(version=iv)
        temp.save()


def generate_point_type_map_migration(apps, schema_editor):
    brick_version = '1.1'
    haystack_version = '3.9.9'
    ivs = ['0.1.7b5', '0.1.9a1']
    for iv in ivs:
        map = generate_point_type_map(brick_version, haystack_version, iv)
        add_map_to_db(map, brick_version, haystack_version, iv)


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_auto_20200824_0225'),
    ]

    operations = [
        migrations.RunPython(add_inference_versions),
        migrations.RunPython(generate_point_type_map_migration)
    ]
