# Generated by Django 3.0.7 on 2020-08-25 01:01

from django.db import migrations

from mapp.resources.migration_utils import generate_brick_equipment_classes


def generate_brick_equipment_classes_migration(apps, schema_editor):
    bv = '1.1'
    generate_brick_equipment_classes(bv)


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_auto_20200824_0225'),
    ]

    operations = [
        migrations.RunPython(generate_brick_equipment_classes_migration)
    ]
