# Generated by Django 3.0.7 on 2020-08-25 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapp', '0013_auto_20200825_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultTemplate',
            fields=[
                ('usecasetemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templater.UseCaseTemplate')),
                ('logic', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            bases=('templater.usecasetemplate',),
        ),
        migrations.CreateModel(
            name='HaystackEquipmentTemplate',
            fields=[
                ('equipmenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templater.EquipmentTemplate')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackEquipmentType')),
                ('points', models.ManyToManyField(to='mapp.HaystackPointType')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackVersion')),
            ],
            bases=('templater.equipmenttemplate',),
        ),
        migrations.CreateModel(
            name='BrickEquipmentTemplate',
            fields=[
                ('equipmenttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templater.EquipmentTemplate')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.BrickEquipmentType')),
                ('points', models.ManyToManyField(to='mapp.BrickPointType')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.BrickVersion')),
            ],
            bases=('templater.equipmenttemplate',),
        ),
        migrations.CreateModel(
            name='HaystackFaultTemplate',
            fields=[
                ('faulttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templater.FaultTemplate')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackEquipmentType')),
                ('points', models.ManyToManyField(to='mapp.HaystackPointType')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackVersion')),
            ],
            bases=('templater.faulttemplate',),
        ),
        migrations.CreateModel(
            name='BrickFaultTemplate',
            fields=[
                ('faulttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='templater.FaultTemplate')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.BrickEquipmentType')),
                ('points', models.ManyToManyField(to='mapp.BrickPointType')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.BrickVersion')),
            ],
            bases=('templater.faulttemplate',),
        ),
    ]
