# Generated by Django 3.0.7 on 2020-08-25 02:28

from django.db import migrations
from templater.resources.migration_utils import add_equipment_templates_migration, add_fault_templates_migration


class Migration(migrations.Migration):

    dependencies = [
        ('templater', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_equipment_templates_migration),
        migrations.RunPython(add_fault_templates_migration),
    ]
