# Generated by Django 3.0.4 on 2020-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalunit',
            name='terminal_unit_type',
            field=models.CharField(choices=[('TU-001', 'VAV Box Cooling Only'), ('TU-002', 'CAV Terminal Unit'), ('None', 'None')], default='TU-001', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airhandler',
            name='cooling_coil_type',
            field=models.CharField(choices=[('CC-001', 'Cooling Coil 1'), ('CC-002', 'Cooling Coil 2'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='airhandler',
            name='heating_coil_type',
            field=models.CharField(choices=[('HC-001', 'Heating Coil 1'), ('HC-002', 'Heating Coil 2'), ('None', 'None')], max_length=100),
        ),
    ]
