# Generated by Django 3.0.7 on 2020-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airhandler',
            name='cooling_coil_type',
            field=models.CharField(choices=[('44', '2-stage DX cooling coil'), ('56', 'Single Stage DX cooling coil'), ('59', 'Modulating chilled water coil'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='airhandler',
            name='discharge_fan_type',
            field=models.CharField(choices=[('4', 'On/off discharge fan'), ('5', 'Variable speed discharge fan'), ('48', '2-speed discharge fan'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='airhandler',
            name='exhaust_fan_type',
            field=models.CharField(choices=[('10', 'On/off exhaust fan'), ('11', 'Variable speed exhaust fan'), ('49', '2-speed exhaust fan'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='airhandler',
            name='heating_coil_type',
            field=models.CharField(choices=[('35', 'Modulating DX heating coil'), ('37', 'Modulating electric heating coil'), ('42', 'Modulating natural gas heating coil'), ('43', '2-stage DX heating coil'), ('45', '2-stage electric heating coil'), ('46', '2-stage natural gas heating coil'), ('55', 'Single Stage DX heating coil'), ('57', 'Modulating hot water coil'), ('58', 'Modulating steam coil'), ('60', 'Single stage electric heating coil'), ('61', 'Single stage natural gas heating coil'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='airhandler',
            name='pre_heat_coil',
            field=models.CharField(choices=[('35', 'Modulating DX heating coil'), ('37', 'Modulating electric heating coil'), ('42', 'Modulating natural gas heating coil'), ('43', '2-stage DX heating coil'), ('45', '2-stage electric heating coil'), ('46', '2-stage natural gas heating coil'), ('55', 'Single Stage DX heating coil'), ('57', 'Modulating hot water coil'), ('58', 'Modulating steam coil'), ('60', 'Single stage electric heating coil'), ('61', 'Single stage natural gas heating coil'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='airhandler',
            name='return_fan_type',
            field=models.CharField(choices=[('7', 'On/off return fan'), ('8', 'Variable speed return fan'), ('50', '2-speed return fan'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='airhandler',
            name='supp_heat_coil',
            field=models.CharField(choices=[('35', 'Modulating DX heating coil'), ('37', 'Modulating electric heating coil'), ('42', 'Modulating natural gas heating coil'), ('43', '2-stage DX heating coil'), ('45', '2-stage electric heating coil'), ('46', '2-stage natural gas heating coil'), ('55', 'Single Stage DX heating coil'), ('57', 'Modulating hot water coil'), ('58', 'Modulating steam coil'), ('60', 'Single stage electric heating coil'), ('61', 'Single stage natural gas heating coil'), ('None', 'None')], max_length=100),
        ),
    ]
