# Generated by Django 3.0.4 on 2020-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='zip',
            field=models.IntegerField(default=80202),
            preserve_default=False,
        ),
    ]
