# Generated by Django 3.0.7 on 2020-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_auto_20200616_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalunit',
            name='terminal_unit_type',
            field=models.CharField(choices=[('1', 'VAV cooling only'), ('2', 'VAV w/modulating hot-water reheat'), ('3', 'VAV w/on-off elec reheat'), ('4', 'VAV w/2-stage elec reheat'), ('5', 'VAV w/modulating elec reheat'), ('6', 'CAV terminal'), ('None', 'None')], max_length=50),
        ),
    ]
