# Generated by Django 3.0.7 on 2020-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_auto_20200616_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='airhandler',
            name='heating_cooling_coil_type',
            field=models.CharField(choices=[('41', 'Variable speed heat pump coil'), ('51', '2-Stage heat pump coil'), ('62', 'Single stage heat pump coil'), ('None', 'None')], default='None', max_length=100),
            preserve_default=False,
        ),
    ]
