# Generated by Django 3.0.7 on 2020-08-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapp', '0008_auto_20200810_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaystackEquipmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackEquipmentType')),
                ('points', models.ManyToManyField(to='mapp.HaystackPointType')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.HaystackVersion')),
            ],
        ),
    ]
