name: Validate Tests Pass
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker compose build
      - name: Test
        run: docker compose run web pytest
